openapi: 3.1.0
info:
  title: Template Swagger API Documentation
  description: |-
    API documentation for the template projects, created by GDSC-DUT. This documentation offers detailed insights into the common API endpoints used across all templates.
  contact:
    email: contact@gdsc.dev
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags:
  - name: authentication
    description: Operations about authentication
  - name: users
    description: Operations about user
paths:
  /auth/login:
    post:
      tags:
        - authentication
      operationId: login
      requestBody:
        description: default email and password, seeded in the database
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@gmail.com
                password:
                  type: string
                  example: password123
              required:
                - email
                - password
      responses:
        "200":
          description: The user is authenticated, and an access token is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                required:
                  - access_token
        "400":
          description: "Return this response if one of the following error occurs: 101"
          content:
            application/json:
              examples:
                error_101_example:
                  $ref: "#/components/examples/error_101_example"
        "401":
          description: "Return this response if one of the following error occurs: 102"
          content:
            application/json:
              examples:
                error_102_example:
                  $ref: "#/components/examples/error_102_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
  /auth/register:
    post:
      tags:
        - authentication
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  example: Pham Tien
                  description: |-
                    ^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$
                    (Starts with one or more letters,
                    allows for characters like spaces,
                    hyphens, apostrophes, commas,
                    and periods within the name,
                    and does not allow trailing spaces)
                email:
                  type: string
                  example: user@gmail.com
                  description: |-
                    ^.*@.*\.(com|net|org)$
                    (The email address must contain at least one character before and after the '@' symbol,
                    and end with an extension like .com, .net, .org.)
                password:
                  type: string
                  example: Password123
                  description: |-
                    ^.*(?=.{7,50})(?=.*\d)(?=.*[A-Z]).*$
                    (The length of the string must be between 7 and 50 characters.
                    It must contain at least one digit.
                    It must contain at least one uppercase letter)
                confirm_password:
                  type: string
                  example: Password123
              required:
                - full_name
                - email
                - password
                - confirm_password
      responses:
        "201":
          description: User registered successfully. Email and full_name are returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user_info"
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  $ref: "#/components/examples/error_104_example"
        "409":
          description: "Return this response if one of the following error occurs: 108"
          content:
            application/json:
              examples:
                error_108_example:
                  $ref: "#/components/examples/error_108_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
  /users:
    get:
      tags:
        - users
      operationId: get_users
      parameters:
        - $ref: "#/components/parameters/page_size_param"
        - $ref: "#/components/parameters/page_param"
      responses:
        "200":
          description: A paginated list of users
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/paginated_total"
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/user_info"
        "400":
          description: "Return this response if one of the following error occurs: 104"
          content:
            application/json:
              examples:
                error_104_example:
                  $ref: "#/components/examples/error_104_example"
        "500":
          description: "Return this response if one of the following error occurs: 103"
          content:
            application/json:
              examples:
                error_103_example:
                  $ref: "#/components/examples/error_103_example"
components:
  schemas:
    user_info:
      type: object
      properties:
        id:
          type: integer
          example: 123
        full_name:
          type: string
          example: Pham Tien
        email:
          type: string
          example: user@gmail.com
      required:
        - id
        - full_name
        - email
    paginated_total:
      type: object
      properties:
        total:
          type: integer
          example: 10
  parameters:
    page_param:
      name: page
      in: query
      description: Page to be displayed
      schema:
        type: integer
        default: 1
        example: 4
    page_size_param:
      name: page_size
      in: query
      description: Number of results per page
      schema:
        type: integer
        default: 10
        example: 1
  examples:
    error_101_example:
      value:
        error_code: 101
        message: The email and password field is required
    error_102_example:
      value:
        error_code: 102
        message: Incorrect email or password
    error_103_example:
      value:
        error_code: 103
        message: An unexpected error occurred on the server
    error_104_example:
      value:
        error_code: 104
        message: Invalid syntax
    error_108_example:
      value:
        error_code: 108
        message: Email already exists
